zarr create
fiji-hpc/hpc-datastore pull request #15
Opened 2023-03-30 20:11 UTC by Thechopsee

2023-04-05 08:12 UTC, xulman commented
Thank You @Thechopsee for the PR. I will review ASAP. Wouldn't you mind in the meantime to post a bit of details about this PR. For example, I had the feeling that the communication protocol got enhanced with `datasetType` parameter, could you briefly document it?

2023-04-05 14:49 UTC, kozusznik commented
I am planning review tomorrow or I will do it next week.

2023-04-21 14:14 UTC, kozusznik requested changes
Is this pull request still actual or may be deleted?

2023-04-21 14:14 UTC, kozusznik commented on dada
Strange file.

2023-04-21 14:14 UTC, kozusznik commented on datasets/0afe3fee-c745-4c9b-8475-50286771c5bb/0/export.n5/attributes.json
Do not place data into the repository.

2023-04-21 14:14 UTC, kozusznik commented on pom.xml
> +            <version>0.0.4</version>
It already exists version 0.0.7

2023-04-21 14:14 UTC, kozusznik commented on src/main/java/cz/it4i/fiji/datastore/DatasetFilesystemHandler.java
> +		if(dataset.getDatasetType().equals("Zarr"))
Do not propagate commented code into Pull request.

2023-04-21 14:14 UTC, kozusznik commented on src/main/java/cz/it4i/fiji/datastore/BlockRequestHandler.java
> +
I suggest remove this blank line(s). The same case in the rest of the file.

2023-04-21 14:14 UTC, kozusznik commented on src/main/java/cz/it4i/fiji/datastore/ApplicationConfiguration.java
> +	public DatasetHandler getDatasetHandlerWR(String uuid) {
Add comments for added methods - it will be understandable what is provided in them.

2023-04-21 14:14 UTC, kozusznik commented on src/main/java/cz/it4i/fiji/datastore/ApplicationConfiguration.java
> +		DatasetRepository datasetDAO=new DatasetRepository();
You can merge this method with following one - from them, call third method that will have second paramaters Supplier<String> typeSupplier.

2023-04-21 14:14 UTC, kozusznik commented on src/main/java/cz/it4i/fiji/datastore/DatasetServerImpl.java
> +import cz.it4i.fiji.datastore.register_service.Dataset;
Is used this import? Because there are only blank lines with changes.

2023-04-21 14:54 UTC, closed without merging

2023-04-25 14:35 UTC, xulman commented
thanks @kozusznik for checking out this PR, also thanks @Thechopsee for working on the zarr stuff