Security v2
fiji-hpc/hpc-datastore pull request #17
Opened 2023-04-20 14:53 UTC by val-metal

2023-05-10 09:13 UTC, kozusznik requested changes

2023-05-10 09:13 UTC, kozusznik commented on dotaz.py
Do not use Czech language for naming files or identifier.

2023-05-10 09:13 UTC, kozusznik commented on doc/SECURITY.md
> +Working bunch of parameters for running from IDE:
Improve documentation, please

2023-05-10 09:13 UTC, kozusznik commented on dotaz.py
> +import requests
Consider moving of this tests into src/test directory from project root

2023-05-10 09:13 UTC, kozusznik commented on dotaz.py
> +import json
consider transform this into JUnit test using 
Apache HttpClient library:
https://mkyong.com/java/apache-httpclient-examples/

2023-05-10 09:13 UTC, kozusznik commented on src/main/java/cz/it4i/fiji/datastore/security/Constants.java
> +	static final String SECURITY_ABLED ="cz.it4i.fiji.datastore.security.able";
add empty line.
Consider using name SECURITY_ON

2023-05-10 09:13 UTC, kozusznik commented on src/main/java/cz/it4i/fiji/datastore/security/OAuthServerEndpoint.java
> +        import javax.ws.rs.*;
use formatter with style for scijava

2023-05-10 09:13 UTC, kozusznik commented on src/main/java/cz/it4i/fiji/datastore/security/OAuthServerEndpoint.java
> +        String vysledek="";
do not use Czech language for identifier names.

2023-05-10 09:13 UTC, kozusznik commented on src/main/java/cz/it4i/fiji/datastore/security/OAuthServerNew.java
> +public class OAuthServerNew extends PanacheEntityBase {
what does mean a suffix "new"

2023-05-10 09:13 UTC, kozusznik commented on src/main/java/cz/it4i/fiji/datastore/security/OAuthServerNew.java
> +    public String BCSerlialize(){
what does mean name BCSerlialize
consider using java code conventions:
https://www.oracle.com/technetwork/java/codeconventions-150003.pdf

method identifiers starts with small letter.

consider override to toString method.

2023-05-10 09:13 UTC, kozusznik commented on src/main/java/cz/it4i/fiji/datastore/security/OAuthServerNew.java
> +    public OAuthServerNew()
consider using lombok annotation AllArgsConstructor, NoArgCOnstructor.

2023-05-10 09:13 UTC, kozusznik commented on src/main/java/cz/it4i/fiji/datastore/security/OAuthServerService.java
> +            return new ArrayList<OAuthServerNew>();
consider using Collections.emptyList

2023-05-10 09:13 UTC, kozusznik commented on src/main/java/cz/it4i/fiji/datastore/security/OAuthServerService.java
> +        return entityManager.createQuery("SELECT os FROM OAuthServerNew os", OAuthServerNew.class)
consider using OAuthServerNew.findAll

2023-05-10 09:13 UTC, kozusznik commented on src/main/java/cz/it4i/fiji/datastore/security/OAuthUserEndpoint.java
> +            //TODO Anonimize tokens
consider setting a null value.

2023-05-10 09:13 UTC, kozusznik commented on src/main/java/cz/it4i/fiji/datastore/security/OAuthUserNew.java
> +package cz.it4i.fiji.datastore.security;
same comments as for OAuthServer

2023-05-10 09:13 UTC, kozusznik commented on src/main/java/cz/it4i/fiji/datastore/security/OAuthUserService.java
> +         return entityManager.createQuery("SELECT os FROM OAuthUserNew os", OAuthUserNew.class)
consider using OAuthUser.findAll()

2023-05-10 09:13 UTC, kozusznik commented on src/main/java/cz/it4i/fiji/datastore/security/SecurityEndpoint.java
> +	@GET
it should be done automatically after changes.

2023-05-10 09:13 UTC, kozusznik commented on src/main/java/cz/it4i/fiji/datastore/security/OAuthGroup.java
> +    @ElementCollection
There is User and Dataset so use association instead of ElementCollection.

2023-05-10 09:13 UTC, kozusznik commented on src/main/java/cz/it4i/fiji/datastore/security/OAuthGroupEndpoint.java
> +    public Response createOAuthGroup(OAuthGroup group) {
use DTO object in REST controller

2023-05-10 09:13 UTC, kozusznik commented on src/main/java/cz/it4i/fiji/datastore/security/OAuthGroupEndpoint.java
> +    public Response createOAuthGroup(OAuthGroup group) {
Consider using http://modelmapper.org for mapper creation.

2023-05-10 09:13 UTC, kozusznik commented on src/main/java/cz/it4i/fiji/datastore/security/OAuthServerNew.java
> +public class OAuthServerNew extends PanacheEntityBase {
Consider using existing class User.

2023-05-10 09:13 UTC, kozusznik commented on src/main/java/cz/it4i/fiji/datastore/security/OAuthUserEndpoint.java
> +        Gson gson = new Gson();
Consider using already used mechanism when DTO objrecy is returned and automacally converted to JSON

2023-05-10 09:13 UTC, kozusznik commented on src/main/java/cz/it4i/fiji/datastore/security/OAuthUserEndpoint.java
> +    @Path("/json")
Consider using standard convention for forming REST API - requested type of data probably should not be part of a path.

2023-05-10 09:13 UTC, kozusznik commented on src/main/java/cz/it4i/fiji/datastore/security/OAuthUserEndpoint.java
> +    @Path("/{client_id}")
Consider using constants for naming parameters in HTTP path

2023-05-10 09:13 UTC, kozusznik commented on src/main/java/cz/it4i/fiji/datastore/security/PermissionType.java
> +    RW("rw"); // Read-Write
should be used with EnumSet when we use Read in conjuction with write.

2023-05-10 09:13 UTC, kozusznik commented on src/main/java/cz/it4i/fiji/datastore/security/SecurityEndpoint.java
> +		@PathParam(OAUTH_SERVER) String oauthServer, @QueryParam(CODE) String code,String device_id,String device_name)
how is binded device_id and device_name and what does it mean?

2023-05-10 09:13 UTC, kozusznik commented on src/main/java/cz/it4i/fiji/datastore/security/SecurityRegistry.java
> +	public List<String> getServerAliases()
servers should be also persisted in DB.

2023-05-10 09:13 UTC, kozusznik commented on start-server-https.cmd
> +set myVar="C:\Users\ValMe\Documents\GitHub\hpc-datastore"
enviromental dependent information should not be in git.
Similar thinks is solved that you create template and commit it. Whilst file that should is derived from a template is mentioned in .gitignore.

2023-05-10 09:13 UTC, kozusznik commented on src/main/java/cz/it4i/fiji/datastore/security/SecurityRegistry.java
> +			String[] serversTokens = getProperty(SECURITY_SERVERS).split(";");
Use security properties for an initialisation of an empty database. After that ignore it. For reading data use only db.

2023-05-10 09:16 UTC, kozusznik requested changes

2023-05-10 09:16 UTC, kozusznik commented on myDb.mv.db
Consider remove data from git and add its file name to gitignore.

2023-05-10 09:16 UTC, kozusznik commented on src/main/java/cz/it4i/fiji/datastore/security/GroupsAuthentication.java
How it works? Something missing for me.

2023-05-19 14:27 UTC, kozusznik requested changes

2023-05-19 14:27 UTC, kozusznik commented on src/main/java/cz/it4i/fiji/datastore/security/SecurityRegistry.java
> +			List<Integer> userids=groups.get(i).getUsersIDs();
Compilation error

2023-05-19 14:27 UTC, kozusznik commented on src/main/java/cz/it4i/fiji/datastore/security/SecurityRegistry.java
> +				String serialized_user=user.get(userids.get(j)).BCSerlialize_user();
Compilation error.

2023-05-19 14:27 UTC, kozusznik commented on src/main/java/cz/it4i/fiji/datastore/security/SecurityRegistry.java
> +			list_user.add(list_all_users.get(i).BCSerlialize_user().split(";"));
compilation error

2023-05-19 14:32 UTC, val-metal commented
To je zvláštní. Zkusím se na to co nejdříve podívat.

2023-05-19 14:40 UTC, kozusznik requested changes

2023-05-19 14:40 UTC, kozusznik commented on src/main/java/cz/it4i/fiji/datastore/security/OAuthUserNew.java
> +public class OAuthUserNew extends PanacheEntityBase {
Is PanacheEntityRepository necessary? I think, there is used only EntityManager.

2023-05-19 14:40 UTC, kozusznik commented on src/main/java/cz/it4i/fiji/datastore/security/OAuthUserNew.java
> +    private String ClientSecret;
Respect Code Convention according to names of Java identifiers 
https://www.oracle.com/java/technologies/javase/codeconventions-namingconventions.html

2023-05-29 08:13 UTC, merged